### ISSUE TITLE
求大神贴出gsnova部署到heroku的详细步骤

### ISSUE THREAD

**Issue by lucaskeen** [wangyi2005/gsnova-heroku#1]
@wangyi2005 求大神贴出gsnova部署到heroku的详细步骤

**Comment by wangyi2005** [comment]
1.注册 heroku。
2.点击 deploy to heroku
3.根据提示deploy。
4.下载客户端。https://github.com/yinqiwen/gsnova/releases，注意只能用 0.32.0 版本。

**Comment by lucaskeen** [comment]
@wangyi2005 多谢大神！Heroku已经部署好正常工作了，但是PC客户端连不上：

![image](https://user-images.githubusercontent.com/25589008/37703888-22ca3512-2d32-11e8-883c-b29b647e7818.png)

我只改了client.json里面2个地方：

1. "Cipher":{"Method":"auto", "Key":"My Key...", "User": "gsnova"},
	"Mux":{
		"MaxStreamWindow": "1024K",
		"StreamMinRefresh":"64K"
	},

"User": "gsnova" 这一项是原来就有的，我也没在Heroku服务端设置过这一项，保留在客户端配置里不知道有没有影响

2. "Channel":[
		{
		    "Enable":true,
			"Name":"heroku-websocket",
			//Allowed server url with schema 'http/http2/https/ws/wss/tcp/tls/quic/kcp/ssh'
			//"ServerList":["quic://1.1.1.1:48101"],
			"ServerList":["wss://my-gsnova.herokuapp.com"],
			//"ServerList":["tcp://127.0.0.1:18080"],
			//"ServerList":["ssh://root@1.1.1.1:22?key=./PPP"],

我用的SwitchyOmega管理代理，不知道设置对不对：

![gsnova-client](https://user-images.githubusercontent.com/25589008/37703734-a430a416-2d31-11e8-9d43-1d12bafb6fd4.png)

麻烦大神帮看一下，谢谢！

**Comment by wangyi2005** [comment]
端口换成48101

**Comment by lucaskeen** [comment]
@wangyi2005 是把SwitchyOmega设置的端口换成48101吗？试过了，还是不行，同样的错误。把SwitchyOmega关掉彻底不用也不行...还有没有别的地方要改的？

![image](https://user-images.githubusercontent.com/25589008/37749496-21e0e25e-2dc3-11e8-867b-af44f7931ab0.png)

![image](https://user-images.githubusercontent.com/25589008/37749601-a2ba3704-2dc3-11e8-8667-e6f99320e5c2.png)
